
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

set -g status-style 'bg=#ff0000,fg=#ffffff'
set -g status-left '#{?client_prefix,#[bg=#0001ff]#[fg=#ff0000]  #[bg=#ff0000]#[fg=#0001ff],#[bg=#ff0000]   }'
set -g status-justify centre
set -g status-right ' Braves: #(~/tools/dotfiles/scripts/braves-record.sh) '
set -g status-right-style 'bg=#0001ff'
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on
set -g status-interval 5

bind r source-file ~/.tmux.conf
